### ISSUE TITLE
Problems running the demo due to high VRAM demands

### ISSUE THREAD

**Issue by SirKero** [guiqi134/Area-ReSTIR#2]
I have problems running the demo, as Area ReSTIR seems to allocate around 12GB of VRAM on startup, which makes it unusable to use with my 8GB card. (Combined with the Bistro scene it uses ~14.5GB, which seems excessively high). Most of the memory allocation seems to come from the resampling resources `initResamplingResources(...) [Line449, AreaReSTIR.cpp]`.

Is the high memory usage due to the prototype nature of this implementation or does Area ReSTIR need so much memory? Are there settings that could be changed to reduce memory consumption?

**Comment by guiqi134** [comment]
The quick answer is YES. Compare to RTXDI, this high memory usage is mostly caused by two parts: (1) nearly no resource packing is implemented in this prototype and (2) the optimization part (`TemporalMSAATracePrimaryRays`) for robust fractioanl temporal reusing stores some additional (almost can be redundent) buffers to avoid the artifacts in some edge cases. Quick prototype is one reason for not doing the packing. Another is packing the data like normal may cause noticable bias in Area ReSTIR. 

I have pushed a new committ for an ad-hoc fix here. You can simply turn off the optimization mode by adding `"optimizeShift2RIS" : False` to `PathTracerAreaReSTIR_BistroDemo.py` (now, ~7.1GB device memory in total will be used):

![image](https://github.com/user-attachments/assets/701516c3-471d-4819-b725-a271ed79fddd)

And you can also turn on/off this option in rendered UI here, but it's going to exceed 8GB (~9.1GB will be used).

![image](https://github.com/user-attachments/assets/e669689f-ce25-435f-9d39-2cf5e4a6580d)

However, in this case, it'll increase the performance cost. I'll later push another version to include our unstable optimization code for robust reuse, which I think only needs ~7.3GB memory, but it may break on glossy surfaces like Zero Day scene.

**Comment by SirKero** [comment]
Thanks for the reply, it works now as long as I keep the "Optimize Shift 2RIS" option off.

However, I found two slight problems with the "profiles" widget `[Line 259-278 , AreaReSTIR.cpp]` which you probably want to fix:
- std::format is c++20 standard but Falcor is set to c++17, so it will not compile by default. I would just change the widget fields to e.g.: `group.text("Reservoir buffer size: " + formatByteSize(mDirectLightingResources.pReservoirs->getSize()));`
- If any of the resources in this group are `nullptr`, Mogwai will crash when expanding the group. Easy fix is to check beforehand if the resource is valid e.g.: 
`if(mDirectLightingResources.pTemporalMISPDFs)`
`     group.text("MIS PDFs data buffer size: " + formatByteSize(mDirectLightingResources.pTemporalMISPDFs->getSize()));`

Also another question. Do you consider adding the option to turn Area ReSTIR part off and use ReSTIR DI in your prototype? That would enable easier quality comparisons and make performance comparisons more fair, as you use an unoptimized version of ReSTIR DI. 
Currently, I can only compare it against the RTXDI framework where render times on Bistro are `220ms` (Area ReSTIR) vs `17ms` (RTXDI) on an RTX 3070Ti for the ReSTIR part, which seems quite unfair.

**Comment by guiqi134** [comment]
Thanks for pointing these out. I usually manually switch AreaReSTIR project properties to use C++20 standard in VS, but I think using C++17 standard would be more competiable for others, so I have updated this. 

> Do you consider adding the option to turn Area ReSTIR part off and use ReSTIR DI in your prototype?

I think there are settings/buttons that could switch between them:
- Press Key "1" for ReSTIR DI and Press Key "2" for Area ReSTIR.
- To partially turn on/off reusing for DoF or AA, you can use `Reusing camera lens sample` and `Reusing subpixel sample` to control. (see image 1)
- You can also control this by setting the value of `reuseLensSample` and `reuseSubpixelSample` in the .py file (see image 2)

![image](https://github.com/user-attachments/assets/8796a2ef-937e-4d3b-ae67-93e2eb4e3ae5)

![image](https://github.com/user-attachments/assets/fde2f40d-ef70-4c4c-8e0b-12258dbe7dce)

**Comment by SirKero** [comment]
Thanks!
That makes comparisons a lot easier.
